spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trablock?serverTimezone=Asia/Seoul
    username: root
    password: ltyxodus7
    driver-class-name: com.mysql.cj.jdbc.Driver

  img:
    tenantId: 92bb02eefaa74ad6a53a63ebc9abba2f
    username: heuirr22@naver.com
    password: 1234
    authUrl: https://api-identity.infrastructure.cloud.toast.com/v2.0
    storageUrl: https://api-storage.cloud.toast.com/v1/AUTH_92bb02eefaa74ad6a53a63ebc9abba2f
    containerName: trablock


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    defer-datasource-initialization: true

  security:
    user:
      name: user
      password: 1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: trablock2022@gmail.com
    password: mdoayaxlsjvbizpc
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

file:
  upload-dir: ./image
